server-data/resources/[esx_addons]/esx-qalle-jail/client/client.lua, server-data/resources/[esx_addons]/esx-qalle-jail/fxmanifest.lua, server-data/resources/[esx_addons]/esx-qalle-jail/locales/en.lua, server-data/resources/[esx_addons]/esx-qalle-jail/locales/it.lua, server-data/resources/[esx_addons]/esx-qalle-jail/server/server.lua
* Have you followed the guidelines in our Contributing document?
* Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
1. Does your submission pass tests?
2. Have you lint your code locally prior to submission?
* Have you added an explanation of what your changes do and why you'd like us to include them?
* Have you written new tests for your core changes, as applicable?
* Have you successfully ran tests with your changes locally?
=> refactor: (esx-qalle-jail) translated new strings through locales folder

.github/CHANGELOG.md, .github/PULL_REQUEST_TEMPLATE.md, server-data/resources/[phone]/pma-voice/client/init/main.lua, server-data/resources/[phone]/pma-voice/client/module/phone.lua, server-data/resources/[phone]/pma-voice/client/module/radio.lua, server-data/resources/[phone]/pma-voice/voice-ui/pnpm-lock.yaml
2. [x] Have you lint your code locally prior to submission?
=> fix: corrected pull request form template + chore: updates for the pma_voice resource

.github/CHANGELOG.md, server-data/resources/[esx_addons]/BasicItem/client/main.lua, server-data/resources/[esx_addons]/BasicItem/locales/it.lua, server-data/resources/[esx_addons]/BasicItem/server/main.lua, server-data/resources/[ox]/ox_inventory/data/shops.lua
2. [x] Have you lint your code locally prior to submission?
=> chore: code cleanup and fixes + remove store dmvshool

.github/CHANGELOG.md, server-data/resources/[ox]/ox_inventory/data/shops.lua, server-data/resources/[ox]/ox_inventory/data/stashes.lua
[ox_inventory\data\shops.lua]: chore: the possibility of purchasing the radio has been added
[ox_inventory\data\stashes.lua]: fix: removed the inventory for the taxi job as it was included in the esx_taxijob resource
=> chore:  new features and implementations for ox_inventory

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_ballasjob/README.md, server-data/resources/[bpt_addons]/bpt_ballasjob/client/main.lua, server-data/resources/[bpt_addons]/bpt_ballasjob/config.lua, server-data/resources/[bpt_addons]/bpt_ballasjob/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_ballasjob/locales/en.lua, server-data/resources/[bpt_addons]/bpt_ballasjob/locales/it.lua, server-data/resources/[bpt_addons]/bpt_ballasjob/server/main.lua, server-data/resources/[ox]/ox_inventory/data/stashes.lua
=> refactor: bpt_ballasjob inventory implementation

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua, server-data/resources/[bpt_addons]/bpt_ammujob/locales/en.lua, server-data/resources/[bpt_addons]/bpt_ammujob/locales/it.lua
=> fix: Fixed the problem that prevented the creation of invoices

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_dustman/README.md, server-data/resources/[bpt_addons]/bpt_dustman/client/main.lua, server-data/resources/[bpt_addons]/bpt_dustman/config.lua, server-data/resources/[bpt_addons]/bpt_dustman/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_dustman/locales/en.lua, server-data/resources/[bpt_addons]/bpt_dustman/locales/it.lua, server-data/resources/[bpt_addons]/bpt_dustman/server/main.lua, server-data/resources/[ox]/ox_inventory/data/stashes.lua
=> refactor: bpt_dustman inventory implementation

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_fisherman/README.md, server-data/resources/[bpt_addons]/bpt_fisherman/client/main.lua, server-data/resources/[bpt_addons]/bpt_fisherman/config.lua, server-data/resources/[bpt_addons]/bpt_fisherman/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_fisherman/locales/en.lua, server-data/resources/[bpt_addons]/bpt_fisherman/locales/it.lua, server-data/resources/[bpt_addons]/bpt_fisherman/server/main.lua, server-data/resources/[ox]/ox_inventory/data/stashes.lua
=> refactor: bpt_fishermanjob inventory implementation

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_hud/README.md, server-data/resources/[bpt_addons]/bpt_hud/html/style.js, server-data/resources/[bpt_addons]/bpt_hud/html/ui.html
=> chore:  push for version 1.0.0

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_importjob/README.md, server-data/resources/[bpt_addons]/bpt_importjob/client/main.lua, server-data/resources/[bpt_addons]/bpt_importjob/config.lua, server-data/resources/[bpt_addons]/bpt_importjob/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_importjob/locales/en.lua, server-data/resources/[bpt_addons]/bpt_importjob/locales/it.lua, server-data/resources/[bpt_addons]/bpt_importjob/server/main.lua, server-data/resources/[ox]/ox_inventory/data/stashes.lua
=> refactor: bpt_importjob inventory implementation

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_crafting/config.lua, server-data/resources/[bpt_addons]/bpt_loadscreen/LICENSE, server-data/resources/[bpt_addons]/bpt_loadscreen/README.md, server-data/resources/[bpt_addons]/bpt_lumberjack/README.md, server-data/resources/[bpt_addons]/bpt_lumberjack/client/main.lua, server-data/resources/[bpt_addons]/bpt_lumberjack/config.lua, server-data/resources/[bpt_addons]/bpt_lumberjack/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_lumberjack/locales/en.lua
=> fix: bpt_lumberjack fixed typos and removed unused code

.github/CHANGELOG.md, server-data/resources/[bpt_addons]/bpt_vehicletax/LICENSE, server-data/resources/[bpt_addons]/bpt_vehicletax/README.md, server-data/resources/[bpt_addons]/bpt_vehicletax/config.lua, server-data/resources/[bpt_addons]/bpt_vehicletax/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_vehicletax/locales/en.lua, server-data/resources/[bpt_addons]/bpt_vehicletax/server/server.lua
=> chore: bpt_vehicletax update to version 1.0.0

.github/CHANGELOG.md, server-data/resources/[maps]/CayoTwoIslands/fxmanifest.lua, server-data/resources/[maps]/CayoTwoIslands/scripts/blips.lua, server-data/resources/[maps]/CayoTwoIslands/scripts/zones.lua
- The server build must be the latest. You should check it and update it at least once a month
- The server MUST be on gamebuild 2189 or later for this asset to run correctly
=> fix: nil value (global 'Config')

server-data/resources/[esx]/es_extended/client/main.lua, server-data/resources/[esx]/es_extended/server/functions.lua
=> fix: (es_extended) line contains trailing whitespace

.github/workflows/codeql.yml, server-data/resources/[esx]/es_extended/client/functions.lua, server-data/resources/[esx]/es_extended/client/modules/streaming.lua
Big refactor to client functions with no breaking changes (allegedly). Except for ESX.Game.SpawnObject that returns the object synchronous if no callback provided. (Just a new behaviour, keeps working as used to)
Added new functions:
· ESX.DrawMissionText
· ESX.Game.GetShapeTestResultSync **
· ESX.Game.RaycastScreen **
** Last two are used to improve the performance of ESX.Game.GetVehicleInDirection It already uses a Synchronous Shape Test Result less performant than solution provided.
In streaming functions, ff no callback provided, functions will return the first argument synchronously. if not, first argument will be passed to the callback.
Cache addon resource states instead of checking it every time a function is called
2. [ ] …
=> refactor(es_extended/client/functions.lua) e (es_extended/client/modules/streaming.lua)

server-data/resources/[esx]/es_extended/client/main.lua, server-data/resources/[esx_addons]/esx_ambulancejob/client/job.lua, server-data/resources/[esx_addons]/esx_ambulancejob/client/main.lua, server-data/resources/[esx_addons]/esx_ambulancejob/client/vehicle.lua, server-data/resources/[esx_addons]/esx_ambulancejob/server/main.lua, server-data/resources/[esx_addons]/esx_boat/client/main.lua, server-data/resources/[esx_addons]/esx_boat/client/marker.lua, server-data/resources/[esx_addons]/esx_policejob/client/main.lua, server-data/resources/[esx_addons]/esx_policejob/client/vehicle.lua, server-data/resources/[esx_addons]/esx_policejob/server/main.lua, server-data/resources/[phone]/esx-radio/client.lua, server-data/resources/[phone]/esx-radio/fxmanifest.lua
[fix: (esx_policejob) accessing undefined variable](https://github.com/bitpredator/empiretown/commit/01c383a3962cf9244dc67dbe1e09d6faf11e4f65)
[fix: (esx_boat) undefined variable](https://github.com/bitpredator/empiretown/commit/bd5535fddfb6543c1ac7aa35c171d39daf30b5d8)
[fix: (esx-radio) accessing undefined variable radioProp](https://github.com/bitpredator/empiretown/commit/320df5d9f3ac2e4195a9a943a4d3e759c5065cff)
=> fix: accessing undefined variable +  replace _U with TranslateCap

server-data/resources/[esx]/es_extended/locale.lua, server-data/resources/[esx]/es_extended/server/classes/player.lua, server-data/resources/[esx]/es_extended/server/functions.lua, server-data/resources/[esx]/es_extended/server/main.lua, server-data/resources/[esx]/es_extended/server/modules/actions.lua, server-data/resources/[esx]/es_extended/server/modules/callback.lua, server-data/resources/[esx]/es_extended/server/modules/npwd.lua
=> ♻️ refactor getCoords, and fix lint issues

server-data/resources/[bpt_addons]/bpt_crafting/config.lua, server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
- Import/export work was allowed to manufacture hammers, while dustman work was allowed to recycle used iron cans
- Import/export work was allowed to manufacture hammers, while dustman work was allowed to recycle used iron cans
=> chore: changed crafting options + fix database

server-data/resources/[bpt_addons]/bpt_importjob/config.lua
- Setting the "rumpo3" vehicle as default should resolve the stuck vehicle problem, it would appear that only rumpo vehicles with advertising lettering have this problem.
=> chore: set rumpo3 vehicle as default

server-data/resources/[bpt_addons]/bpt_hud/LICENSE, server-data/resources/[bpt_addons]/bpt_hud/client/carhud.lua, server-data/resources/[bpt_addons]/bpt_hud/client/client.lua, server-data/resources/[bpt_addons]/bpt_hud/client/status.lua, server-data/resources/[bpt_addons]/bpt_hud/fxmanifest.lua
- Use PlayerPedId() instead of GetPlayerPed(-1) to improve performance
=> chore: use PlayerPedId() instead of GetPlayerPed(-1) + fix license

server-data/resources/[bpt_addons]/bpt_policejob/client/main.lua, server-data/resources/[bpt_addons]/bpt_policejob/locales/it.lua, server-data/resources/[esx_addons]/esx_cuffanimation/README.md, server-data/resources/[esx_addons]/esx_cuffanimation/client/main.lua, server-data/resources/[esx_addons]/esx_cuffanimation/config.lua, server-data/resources/[esx_addons]/esx_cuffanimation/fxmanifest.lua, server-data/resources/[esx_addons]/esx_cuffanimation/server/main.lua
=> chore:  implemented handcuff animation

server-data/resources/[esx_addons]/tickets/LICENSE, server-data/resources/[esx_addons]/tickets/README.md, server-data/resources/[esx_addons]/tickets/__install/database.sql, server-data/resources/[esx_addons]/tickets/client/main.lua, server-data/resources/[esx_addons]/tickets/fxmanifest.lua, server-data/resources/[esx_addons]/tickets/nui/css/style.css, server-data/resources/[esx_addons]/tickets/nui/index.html, server-data/resources/[esx_addons]/tickets/nui/js/script.js, server-data/resources/[esx_addons]/tickets/server/main.lua, server-data/resources/[esx_addons]/tickets/shared/bridge.lua, server-data/resources/[esx_addons]/tickets/shared/config.lua, server-data/resources/[esx_addons]/tickets/shared/database.lua, server-data/resources/[esx_addons]/tickets/shared/utilities.lua, server-data/server.cfg
=> feat: feat in game system tickets

server-data/resources/[bpt_addons]/bpt_menu/client/main.lua, server-data/resources/[bpt_addons]/bpt_menu/config.lua
=> chore: implemented support role with some administrative permissions

server-data/resources/[bpt_addons]/bpt_taxijob/server/main.lua
=> refactore: refactored code to make it more readable

server-data/resources/[bpt_addons]/bpt_ambulancejob/client/deathcam.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/client/job.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/client/main.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/client/vehicle.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/config.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/locales/it.lua, server-data/resources/[bpt_addons]/bpt_ambulancejob/server/main.lua
=> refactor: bpt_ambulancejob reconstruction to fix bugs found

.github/workflows/StyLuaGitHubAction.yml, server-data/resources/[bpt_addons]/bpt_menu/client/main.lua, server-data/resources/[bpt_addons]/bpt_menu/config.lua
=> chore: Update the stylua-action workflow to v4 + removed permissions for helpers

server-data/resources/[bpt_addons]/bpt_autovelox/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_autovelox/server/main.lua
Replaced incorrect MySQL:update method with exports.oxmysql:fetch in the autovelox:isVehicleBlocked server callback. The original implementation incorrectly used an update method for a SELECT query, causing runtime errors and blocking proper vehicle plate verification. Now the callback retrieves blocked_for_fine correctly and returns the appropriate response to the client.
=> Fix SQL query in autovelox vehicle block check

server-data/resources/[esx_addons]/esx_garage/nui/js/app.js
This pull request addresses a client-side Cross-Site Scripting (XSS) vulnerability present in the NUI vehicle menu system of the FiveM garage interface.
- Added a `escapeHtml()` utility function to sanitize all user-displayed HTML content.
- Sanitized vehicle model, plate, and serialized props in `getVehicles()` and `getImpoundedVehicles()` before injecting into the DOM using `.html()`.
- Ensured all dynamic strings are safely encoded to prevent script injection or malformed HTML rendering.
Even though FiveM NUI doesn't communicate with the external web, users can manipulate their game client and inject malicious data via the Lua layer or spoofed NUI messages. This change prevents the possibility of client-side code execution due to unsafe HTML rendering.
- This patch is fully backward …
=> Fix XSS Vulnerability in NUI Vehicle Menu (FiveM)

server-data/resources/[esx_addons]/esx_garage/nui/js/app.js
This pull request addresses a client-side cross-site scripting (XSS) vulnerability in the `app.js` file. Previously, user-supplied values such as `veh_model`, `veh_plate`, and `veh_condition` were inserted into the DOM without sanitization, posing a security risk.
Changes:
- Wrapped `data.locales.veh_model`, `veh_plate`, and `veh_condition` with the existing `escapeHtml()` function before DOM insertion.
- Ensured that dynamic text replacements in `.html()` now use sanitized input.
This update ensures safe rendering of user data in the interface and aligns with best practices for secure frontend code.
=> Fix client-side XSS vulnerability in app.js using HTML escaping

server-data/resources/[esx_addons]/esx_garage/client/main.lua, server-data/resources/[esx_addons]/esx_garage/server/main.lua
Refactored the local variable name from vehicle to networkVehicle after using NetworkGetEntityFromNetworkId(vehicle) to enhance code readability and avoid overwriting the original network ID. This change improves clarity and prevents potential logic issues caused by reusing the same variable name for different purposes.
=> ♻️ Improved variable clarity when retrieving network vehicle entity

server-data/resources/[gamemodes]/basic-gamemode/basic_client.lua, server-data/resources/[gamemodes]/basic-gamemode/fxmanifest.lua
This pull request improves the initialization process for client auto-spawning when the map starts.
- Wrapped logic inside `CreateThread` to avoid blocking the main thread.
- Added a small `Wait(500)` delay to prevent race conditions during early client loading.
- Added checks to ensure `spawnmanager` is available before calling its functions.
- Included optional debug logging for easier future troubleshooting.
These changes increase reliability and maintainability, especially in environments where the spawn manager may not be fully initialized immediately upon map load. It prevents potential errors and improves spawn consistency across client sessions.
Feel free to uncomment the debug line if needed for further testing or diagnostics.
**Please describe the changes this …
=> Improve Client Auto-Spawn Initialization on Map Start

server-data/resources/[bpt_addons]/bpt_mining/client/client.lua, server-data/resources/[bpt_addons]/bpt_mining/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_mining/server/server.lua
- Added improved `RemoveNearbyJackhammers` function with `GetGamePool('CObject')` search
- Support for more jackhammer models (`prop_tool_jackham`, `prop_tool_jackhammer`, etc.)
- Added secure delete system with network and mission entity check
- Cleanup now performed in two passes to avoid dropped props
- Fixed bug that prevented the jackhammer generated by the scenery from being removed
- Prevented duplicate/abandoned props near the player
- Added `DEBUG_JACKHAMMER` flag to log found and removed models
- Configurable `CLEANUP_RADIUS` parameter (default: 8.0)
=> Fix: Jackhammer cleanup after mining (correct prop + double pass)

server-data/resources/[bpt_addons]/bpt_wood/LICENSE, server-data/resources/[bpt_addons]/bpt_wood/README.md, server-data/resources/[bpt_addons]/bpt_wood/client/main.lua, server-data/resources/[bpt_addons]/bpt_wood/config.lua, server-data/resources/[bpt_addons]/bpt_wood/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_wood/server/main.lua, server-data/resources/[ox]/ox_inventory/data/items.lua
- Added configurable woodcutting points (config.lua).
- Integration with ox_target for in-game interactions.
- Inventory control system: the player must have an axe as an item to chop.
- Custom axe animation (RPEmotes-style integration).
- Progress bar during chopping with animation loop.
- Wood generation as a reward (Config.WoodItem) with a random amount from configurable values.
- Configurable blips on the map to show woodcutting points.
- Automatic axe prop cleanup upon completion of the action.
- Notifications for success, cancellation, or missing axe.
=> refactor: Woodcutting with Axe, Animations, and Resource Collection

.github/workflows/ESlint.yml
Potential fix for [https://github.com/bitpredator/empiretown/security/code-scanning/663](https://github.com/bitpredator/empiretown/security/code-scanning/663)
To fix this issue, add an explicit `permissions` block to the workflow file. The block should be placed either at the root of the workflow (top-level, recommended for single-job workflows like this one) or inside the individual job definition. The least-privilege setting for most linting-related workflows is `contents: read`, which only allows the workflow to fetch repository files as needed. Should the workflow require further permissions (such as commenting on pull requests), only those write permissions should be added. For the code shown, unless the ESLint action actually creates annotations or writes to pull requests, …
=> Potential fix for code scanning alert no. 663: Workflow does not contain permissions

server-data/resources/[bpt_addons]/bpt_wallet/README.md, server-data/resources/[bpt_addons]/bpt_wallet/client/client.lua, server-data/resources/[bpt_addons]/bpt_wallet/config.lua, server-data/resources/[bpt_addons]/bpt_wallet/fxmanifest.lua, server-data/resources/[bpt_addons]/bpt_wallet/server/server.lua
- Added a configurable item whitelist (`Config.WalletWhitelist`) to control which items can be added to the wallet.
- Implemented a server-side hook on ox_inventory (swapItems) that blocks the insertion of unauthorized items.
- Added a notification via ox_lib to the player if an attempt is made to insert an unauthorized item.
- Improved defensive data handling (`payload.fromSlot`, `payload.toInventory`) to avoid errors and false positives.
- Made the check case-insensitive, reducing issues with item names.
Some players were using the wallet as an extra container for any type of item, causing **abuse and gameplay imbalance**.
With this patch, the wallet becomes consistent with its actual function: to hold only documents and money, preventing exploits and maintaining a more balanced gaming …
=> [FIX/FEATURE] Implemented item whitelist for the wallet (ox_inventory)

server-data/resources/[esx_addons]/cuchi_computer/server/main.lua
- Replaced the **clean money** reward with the **`black_money`` item for Data Heists.
- Direct integration with **ox_inventory**: Dirty money is now added as a **physical item** to the player's inventory.
- Support for both **ESX** and **QBCore**, with consistent handling of the `black_money` item.
- Ensure the `black_money` item is defined in `ox_inventory/data/items.lua` or in a custom file:
```lua
["black_money"] = {
label = "Dirty Money",
weight = 0,
stack = true,
close = true,
description = "Illegally obtained cash"
}
```
- With this change, black_money is no longer an account, but a physical object.
- Check for any third-party scripts that still use black_money as an account.
Discord …
=> 💰 Data Heist Reward Update: black_money as item in ox_inventory
