- server-data/resources/[bpt_addons]/bpt_realisticvehicle/LICENSE
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/README.md
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/client/damage.lua
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/config.lua
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/fxmanifest.lua
code fix with small improvements.
renamed the _resource.lua file to fxmanifest.lua
> refactor+fix(bpt_realisticvehicle  various fixes and improvements)

- server-data/resources/[esx_addons]/jsfour-idcard/client.lua
- server-data/resources/[esx_addons]/jsfour-idcard/html/assets/js/init.js
- server-data/resources/[esx_addons]/jsfour-idcard/html/assets/js/materialize.js
- server-data/resources/[gameplay]/chat/yarn.lock
This PR enables some translations and fixes some security issues
> refactor(Added ability to translate)

- server-data/resources/[esx]/esx_identity/fxmanifest.lua
- server-data/resources/[esx]/esx_identity/html/css/style.css
- server-data/resources/[esx]/esx_identity/html/index.html
- server-data/resources/[esx]/esx_identity/html/js/script.js
removing "jquery " fixes some security issues
> refactor(esx_identity): jquery removal

- server-data/resources/[bpt_addons]/bpt_loadscreen/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/config.js
- Just press the "play" button to play the audio.
> fix(bpt_loadscreen):fixed audio playback problem

- server-data/resources/[ox]/ox_lib/fxmanifest.lua
- server-data/resources/[ox]/ox_lib/imports/math/shared.lua
- server-data/resources/[ox]/ox_lib/locales/et.json
- server-data/resources/[ox]/ox_lib/resource/interface/client/textui.lua
- server-data/resources/[ox]/ox_lib/resource/vehicleProperties/client.lua
- client/vehicleProperties: support extra props
- imports: extended math lib
- client/vehicleProperties: SetVehicleExtra takes bool
- client/vehicleProperties: missing tyres
- client/vehicleProperties: tonumber for extras and tyres
- cleint/textui: cancel showTextUI if text is unchanged
- locales: update et.json
> update: ox-lib version v3.5.0

- server-data/resources/[bpt_addons]/bpt_realisticvehicle/client/damage.lua
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/client/enginesmoke.lua
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/config.lua
- server-data/resources/[bpt_addons]/bpt_realisticvehicle/fxmanifest.lua
- fix waitspace
- config.lua update
- enginesmoke.lua tranlate
> refactor:(bpt_realisticvehicle)

- server-data/resources/[esx_addons]/esx_rpchat/README.md
- server-data/resources/[esx_addons]/esx_rpchat/client/main.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/cs.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/en.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/es.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/fi.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/fr.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/hu.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/it.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/pl.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/si.lua
- server-data/resources/[esx_addons]/esx_rpchat/locales/sv.lua
- server-data/resources/[esx_addons]/esx_rpchat/server/main.lua
Removes the /twt command, as twitters will need to be sent over the phone for a more real experience
> chore:(esx_rpchat): removes the /twt command

- server-data/resources/[esx]/es_extended/server/classes/player.lua
- server-data/resources/[esx]/es_extended/server/commands.lua
Rebuilding the code server :
- [classes/player.lua](https://github.com/bitpredator/empiretown/commit/d426cd376a9cf83b70675be33b34dabf5c18e82c)
- [es_extended\server\commands.lua](https://github.com/bitpredator/empiretown/commit/20fbf332506a44f2bdb34486cf1fff61eb52399a)
- [fix: es_extended\server\commands.lua - fix lint error](https://github.com/bitpredator/empiretown/commit/638d9df2cd1e20ec6eee678ad29ab2c219f7e3ed)
- Code formatting has been improved and various issues reported by CI Lint scanned by code have been resolved.
> refactor: es_extended/server/

- .github/PULL_REQUEST_TEMPLATE.md
>  chore: update .github\PULL_REQUEST_TEMPLATE.md

- .github/CHANGELOG.md
- server-data/resources/[esx_addons]/esx_license/LICENSE
- server-data/resources/[esx_addons]/esx_license/README.md
- server-data/resources/[esx_addons]/esx_license/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_license/server/main.lua
* []Have you followed the guidelines in our Contributing document?
* []Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
1. []Does your submission pass tests?
2. []Have you lint your code locally prior to submission?
* []Have you added an explanation of what your changes do and why you'd like us to include them?
* []Have you written new tests for your core changes, as applicable?
* []Have you successfully ran tests with your changes locally?
> [esx_license\server\main.lua]: Replaced print in esx_license:addLicense

- .github/CHANGELOG.md
- .github/PULL_REQUEST_TEMPLATE.md
- server-data/resources/[phone]/pma-voice/voice-ui/pnpm-lock.yaml
2. [  ]Have you lint your code locally prior to submission?
> bump browserify-sign from 4.2.1 to 4.2.2 in /voice-ui

- .github/CHANGELOG.md
- server-data/resources/[esx_addons]/BOBsHunt/LICENSE
- server-data/resources/[esx_addons]/BOBsHunt/client/functions.lua
- server-data/resources/[esx_addons]/BOBsHunt/client/main.lua
- server-data/resources/[esx_addons]/BOBsHunt/fxmanifest.lua
- server-data/resources/[esx_addons]/BOBsHunt/locales/en.lua
- server-data/resources/[esx_addons]/BOBsHunt/locales/it.lua
- server-data/resources/[esx_addons]/BOBsHunt/server/main.lua
2. [x] Have you lint your code locally prior to submission?
> refactor: code cleaning, various corrections to the code as well as license updates

- .github/CHANGELOG.md
- server-data/resources/[esx_addons]/esx_addoninventory/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_addoninventory/server/classes/addoninventory.lua
- server-data/resources/[esx_addons]/esx_addoninventory/server/main.lua
> chore: check for nil society

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_deliveries/client/main.lua
- server-data/resources/[bpt_addons]/bpt_deliveries/server/main.lua
- server-data/resources/[esx]/esx_multicharacter/client/main.lua
- server-data/resources/[esx_addons]/esx-qalle-jail/client/client.lua
- server-data/resources/[esx_addons]/esx-qalle-jail/client/utils.lua
- server-data/resources/[esx_addons]/esx-qalle-jail/fxmanifest.lua
- server-data/resources/[esx_addons]/esx-qalle-jail/server/server.lua
- server-data/resources/[esx_addons]/esx-radialmenu/client/main.lua
- server-data/resources/[esx_addons]/esx-radialmenu/client/trunk.lua
- server-data/resources/[esx_addons]/esx-radialmenu/fxmanifest.lua
- server-data/resources/[esx_addons]/esx-radialmenu/server/trunk.lua
- server-data/resources/[esx_addons]/esx_dmvschool/client/main.lua
- server-data/resources/[esx_addons]/esx_dmvschool/config.lua
> chore: clean up the code

- .github/CHANGELOG.md
- server-data/resources/[esx]/es_extended/client/common.lua
- server-data/resources/[esx]/es_extended/imports.lua
- server-data/resources/[esx]/es_extended/server/commands.lua
2. [x] Have you lint your code locally prior to submission?
> refactor/fix: cleanup, remove useless code, formatting

- .github/CHANGELOG.md
- server-data/resources/[esx_addons]/esx_joblisting/LICENSE
- server-data/resources/[esx_addons]/esx_joblisting/client/main.lua
- server-data/resources/[esx_addons]/esx_joblisting/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/br.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/de.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/es.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/fi.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/fr.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/hu.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/it.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/nl.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/si.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/sl.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/sr.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/sv.lua
- server-data/resources/[esx_addons]/esx_joblisting/locales/zh-cn.lua
- server-data/resources/[esx_addons]/esx_joblisting/server/main.lua
> refactor: refactor esx_joblisting

- server-data/resources/[esx_addons]/esx_taxijob/client/main.lua
> fix: esx_taxijob fix lint error

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_bakerjob/README.md
- server-data/resources/[bpt_addons]/bpt_bakerjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/config.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/locales/it.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/server/main.lua
- server-data/resources/[ox]/ox_inventory/data/stashes.lua
> refactor: bpt_bakerjob inventory implementation

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_bakerjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/locales/it.lua
> fix: Fixed the problem that prevented the creation of invoices

- server-data/resources/[bpt_addons]/bpt_doorlock/README.md
- server-data/resources/[bpt_addons]/bpt_doorlock/client/main.lua
> chore: bpt_doorlock readme update

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_farmer/README.md
- server-data/resources/[bpt_addons]/bpt_farmer/client/main.lua
- server-data/resources/[bpt_addons]/bpt_farmer/config.lua
- server-data/resources/[bpt_addons]/bpt_farmer/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_farmer/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_farmer/locales/it.lua
> refactor: support for translations through local files

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_loadscreen/css/style.css
- server-data/resources/[bpt_addons]/bpt_loadscreen/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/color-change.js
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/config.js
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/loadingbar.js
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/music-controls.js
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/music-handler.js
- server-data/resources/[bpt_addons]/bpt_loadscreen/js/server-name-changer.js
> chore: bpt_loadscreen improves code formatting

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_streetfight/LICENSE
- server-data/resources/[bpt_addons]/bpt_streetfight/README.md
- server-data/resources/[bpt_addons]/bpt_streetfight/client/client.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/config.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/locales/it.lua
> chore: supports map point through local translation

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_teleport/LICENSE
- server-data/resources/[bpt_addons]/bpt_teleport/README.md
- server-data/resources/[bpt_addons]/bpt_teleport/config.lua
- server-data/resources/[bpt_addons]/bpt_teleport/fxmanifest.lua
> chore:  update bpt_teleport

- .github/CHANGELOG.md
- server-data/resources/[bpt_addons]/bpt_wallet/LICENSE
- server-data/resources/[bpt_addons]/bpt_wallet/README.md
- server-data/resources/[bpt_addons]/bpt_wallet/client/client.lua
- server-data/resources/[bpt_addons]/bpt_wallet/fxmanifest.lua
> chore: bpt_wallet update to version 1.0.0

- .github/CHANGELOG.md
- server-data/resources/[esx]/es_extended/LICENSE
- server-data/resources/[esx]/es_extended/client/functions.lua
- server-data/resources/[esx]/es_extended/fxmanifest.lua
- server-data/resources/[esx]/es_extended/readme.md
- server-data/resources/[esx]/es_extended/server/classes/player.lua
- server-data/resources/[esx]/es_extended/server/functions.lua
> chore: es_extended add underflow check for removeAccountMoney

- .github/CHANGELOG.md
- server-data/resources/[esx]/esx_context/LICENSE
- server-data/resources/[esx]/esx_context/README.md
- server-data/resources/[esx]/esx_context/fxmanifest.lua
- server-data/resources/[esx]/esx_context/index.html
- server-data/resources/[esx]/esx_context/main.lua
> chore: esx_context update to version 1.0.0

- .github/CHANGELOG.md
- server-data/resources/[esx]/esx_menu_default/LICENSE
- server-data/resources/[esx]/esx_menu_default/README.md
- server-data/resources/[esx]/esx_menu_default/client/main.lua
- server-data/resources/[esx]/esx_menu_default/fxmanifest.lua
- server-data/resources/[esx]/esx_menu_default/html/css/app.css
- server-data/resources/[esx]/esx_menu_default/html/js/app.js
- server-data/resources/[esx]/esx_menu_default/html/js/mustache.min.js
- server-data/resources/[esx]/esx_menu_default/html/ui.html
> chore: esx_menu_default update to version 1.0.0

- server-data/resources/[esx]/esx_menu_list/LICENSE
- server-data/resources/[esx]/esx_menu_list/README.md
- server-data/resources/[esx]/esx_menu_list/client/main.lua
- server-data/resources/[esx]/esx_menu_list/fxmanifest.lua
- server-data/resources/[esx]/esx_menu_list/html/css/app.css
- server-data/resources/[esx]/esx_menu_list/html/js/app.js
- server-data/resources/[esx]/esx_menu_list/html/js/mustache.min.js
- server-data/resources/[esx]/esx_menu_list/html/ui.html
> chore: esx_menu_list update to version 1.0.0

- .github/CHANGELOG.md
- server-data/[SQL]/es_extended.sql
- server-data/resources/[esx]/esx_multicharacter/client/main.lua
> fix:  fixed problem which prevented the menu from opening

- server-data/resources/[ox]/oxmysql/dist/build.js
- server-data/resources/[ox]/oxmysql/fxmanifest.lua
> update: oxmysql version '2.7.7'

- .github/workflows/formatt-all.yml
> feat: formatt-all.yml

- .github/workflows/formatt-all.yml
- server-data/resources/[maps]/CayoTwoIslands/fxmanifest.lua
- server-data/resources/[maps]/CayoTwoIslands/scripts/blips.lua
> 🎨 Run formatter

- server-data/resources/[esx_addons]/esx_banking/client/main.lua
- server-data/resources/[esx_addons]/esx_banking/config.lua
- server-data/resources/[esx_addons]/esx_banking/server/main.lua
- server-data/resources/[esx_addons]/esx_status/client/classes/status.lua
- server-data/resources/[esx_addons]/esx_status/client/main.lua
- server-data/resources/[esx_addons]/esx_status/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_status/server/classes/status.lua
- server-data/resources/[esx_addons]/esx_status/server/main.lua
> chore: esx_status 🎨 Run formatter

- server-data/resources/[bpt_addons]/bpt_ammujob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/localization/bpt_ammujob_it.sql
- Created database for the Italian language
- Translated the database into the main directory in English
- fxmanifest updated to version 1.0.1
> chore: bpt_ammujob database update

- server-data/resources/[bpt_addons]/bpt_bakerjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/localization/bpt_bakerjob_it.sql
- Created database for the Italian language
- Translated the database into the main directory in English
- fxmanifest updated to version 1.0.1
- Improved client-side code formatting
> chore: bpt_bakerjob database update + 🎨 Run formatter

- server-data/resources/[bpt_cars]/pack_cars.sql
- server-data/resources/[bpt_cars]/pack_cars/data/p911r/carcols.meta
- server-data/resources/[bpt_cars]/pack_cars/data/p911r/carvariations.meta
- server-data/resources/[bpt_cars]/pack_cars/data/p911r/dlctext.meta
- server-data/resources/[bpt_cars]/pack_cars/data/p911r/handling.meta
- server-data/resources/[bpt_cars]/pack_cars/data/p911r/vehicles.meta
- server-data/resources/[bpt_cars]/pack_cars/fxmanifest.lua
- server-data/resources/[bpt_cars]/tagt3flat6/fxmanifest.lua
- Created database
- fxmanifest updated to version 1.0.1
- Improved code formatting
> chore: pack_cars database creation and code formatting

- server-data/resources/[esx_addons]/esx_ambulancejob/client/job.lua
- server-data/resources/[ox]/oxmysql/dist/build.js
- server-data/resources/[ox]/oxmysql/fxmanifest.lua
- server-data/resources/[sqz]/sqz_carkeys/fxmanifest.lua
- server-data/resources/[sqz]/sqz_carkeys/server/server.lua
- server-data/resources/[sqz]/sqz_carkeys/sql.sql
> chore: update oxmysql + Change GetClosestVehicle native to ESX.Game.GetClosestVehicle

- server-data/[SQL]/es_extended.sql
> chore: database update

- .github/workflows/codeql.yml
> chore: update codeql workflow

- server-data/resources/[esx]/es_extended/client/main.lua
- server-data/resources/[esx]/es_extended/client/modules/callback.lua
- server-data/resources/[esx]/es_extended/fxmanifest.lua
- server-data/resources/[esx]/es_extended/server/main.lua
- server-data/resources/[esx]/esx_multicharacter/client/main.lua
> refactor(es_extended) general code refactor and await callbacks

- server-data/resources/[bpt_addons]/bpt_unicornjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_unicornjob/server/main.lua
- server-data/resources/[bpt_addons]/bpt_vehicletax/server/server.lua
> chore(deps)

- server-data/resources/[sqz]/sqz_rental/client.lua
- server-data/resources/[sqz]/sqz_rental/config.lua
- server-data/resources/[sqz]/sqz_rental/fxmanifest.lua
- server-data/resources/[sqz]/sqz_rental/locales/en.lua
- server-data/resources/[sqz]/sqz_rental/server.lua
- Native support for translations
- Improved code formatting
> refactor: (sqz_rental):  partial reconstruction of the code

- server-data/resources/[esx_addons]/BasicItem/client/main.lua
- server-data/resources/[esx_addons]/BasicItem/fxmanifest.lua
- server-data/resources/[esx_addons]/BasicItem/server/main.lua
> fix: (BasicItem\client & server) accessing undefined variable

- server-data/resources/[bpt_addons]/bpt_crafting/client/main.lua
> fix: (bpt_crafting) fix error no such export SendAlert

- .github/labeler.yml
- server-data/resources/[esx_addons]/BasicItem/client/main.lua
- server-data/resources/[esx_addons]/BasicItem/fxmanifest.lua
> fix: use bpt_idcard instead of jsfour-idcard

- server-data/resources/[bpt_addons]/bpt_basicItem/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_basicItem/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_basicItem/locales/it.lua
> fix:  locales files are no longer needed in this code

- server-data/resources/[esx_addons]/esx_scoreboard/client/main.lua
- server-data/resources/[esx_addons]/esx_scoreboard/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_scoreboard/html/listener.js
- server-data/resources/[esx_addons]/esx_scoreboard/html/scoreboard.html
- server-data/resources/[esx_addons]/esx_scoreboard/html/style.css
- server-data/resources/[esx_addons]/esx_scoreboard/server/main.lua
> feat: esx_scoreboard

- server-data/resources/[ox]/ox_inventory/data/shops.lua
> chore: new shops created and restored

- server-data/resources/[wasabi]/wasabi_mining/configuration/config.lua
- server-data/resources/[wasabi]/wasabi_oxshops/LICENSE
- server-data/resources/[wasabi]/wasabi_oxshops/client/client.lua
- server-data/resources/[wasabi]/wasabi_oxshops/configuration/config.lua
- server-data/resources/[wasabi]/wasabi_oxshops/configuration/strings.lua
- server-data/resources/[wasabi]/wasabi_oxshops/fxmanifest.lua
> chore: implemented the possibility of collecting gold + point of purchase for the armory

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
- server-data/resources/[bpt_addons]/bpt_menu/client/main.lua
- server-data/resources/[bpt_addons]/bpt_menu/config.lua
> chore: bpt_crafting\config.lua ( modify the recipe for creating the ap_pistol)  

- server-data/resources/[esx]/esx_notify/Notify.lua
- server-data/resources/[esx]/esx_progressbar/Progress.lua
> refactor: used cached esx ped and fixed some lua ls annotations

- server-data/resources/[bpt_addons]/bpt_addonaccount/server/classes/addonaccount.lua
- server-data/resources/[bpt_addons]/bpt_addonaccount/server/main.lua
> feat: added exports to get accounts

- server-data/resources/[bpt_addons]/bpt_billing/client/main.lua
- server-data/resources/[bpt_addons]/bpt_billing/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_billing/server/main.lua
- server-data/resources/[bpt_addons]/bpt_crafting/html/script.js
- server-data/resources/[esx]/esx_textui/nui/js/script.js
- server-data/resources/[phone]/esx-radio/html/js/script.js
> refactor: Improved code style respecting ESLint rules

- server-data/[SQL]/es_extended.sql
> chore: update the database for version 1.0.1

- .github/workflows/assign-to-one-project.yml
> feat: .github\workflows\assign-to-one-project.yml

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/assign-to-one-project.yml
> chore: simplified the compilation of the PULL_REQUEST_TEMPLATE file

- .github/workflows/assign-to-one-project.yml
> fix: .github\workflows\assign-to-one-project.yml

- .github/workflows/assign-to-one-project.yml
> chore: new fix .github\workflows\assign-to-one-project.yml

- .gitignore
-  Updated the files and folders to ignore when pushing to the repository
> chore: updates which files and folders to ignore

- server-data/server.cfg
- Removed the resource package launcher [bpt_cars] as it is no longer present
> fix: server-data\server.cfg [bpt_cars] is no longer present

- server-data/resources/[esx]/es_extended/server/main.lua
> fix: (es_extended\server\main.lua) fix player data name value

- server-data/inventory.cfg
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_importjob/config.lua
- Changed the spawn height for the import company vehicle
- Modified knife crafting recipe
- Blocked checking for updates for ox_inventory
> chore + fix: modified knife crafting recipe - blocks checking for ox_inventory updates - spawn height changed 

- server-data/resources/[bpt_addons]/bpt_billing/server/main.lua
- server-data/resources/[bpt_addons]/bpt_taxijob/server/main.lua
- server-data/resources/[esx]/es_extended/server/paycheck.lua
- server-data/resources/[esx_addons]/esx_property/server/main.lua
- Fixed issue with invoices not being sent and posted
> fix:  invoices were not sent and recorded

- .github/dependabot.yml
> chore:  update dependabot workflow

- server-data/resources/[bpt_addons]/bpt_ambulancejob/config.lua
- Fix for inability to self-revive after pressing the "E" key
> fix:  impossible to self-resuscitate

- server-data/resources/[bpt_addons]/bpt_farmer/client/main.lua
- server-data/resources/[bpt_addons]/bpt_hunting/client/functions.lua
- server-data/resources/[bpt_addons]/bpt_hunting/client/main.lua
- server-data/resources/[bpt_addons]/bpt_idcard/LICENSE
- server-data/resources/[bpt_addons]/bpt_idcard/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_lumberjack/client/main.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/client/client.lua
- server-data/resources/[bpt_addons]/bpt_streetfight/server/server.lua
> chore: update of some natives

- server-data/resources/[bpt_addons]/bpt_pointsell/LICENSE
- server-data/resources/[bpt_addons]/bpt_pointsell/README.md
- server-data/resources/[bpt_addons]/bpt_pointsell/client/main.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/config.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/locales/it.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/server/main.lua
> feat: bpt_pointsell

- server-data/resources/[bpt_addons]/bpt_crafting/html/script.js
- server-data/resources/[bpt_addons]/bpt_dmvschool/html/scripts.js
- server-data/resources/[bpt_addons]/bpt_hunting/client/functions.lua
- server-data/resources/[bpt_addons]/bpt_hunting/client/main.lua
- server-data/resources/[esx]/vSync/server/server.lua
- server-data/resources/[esx_addons]/esx_scoreboard/client/main.lua
- server-data/resources/[esx_addons]/esx_scoreboard/html/listener.js
- server-data/resources/[ox]/ox_inventory/data/items.lua
- server-data/resources/[phone]/esx-radio/client.lua
- server-data/resources/[phone]/esx-radio/config.lua
- server-data/resources/[phone]/esx-radio/server.lua
- server-data/resources/[phone]/pma-voice/server/main.lua
- server-data/resources/[phone]/pma-voice/server/module/phone.lua
- server-data/resources/[phone]/pma-voice/server/module/radio.lua
- server-data/resources/[phone]/pma-voice/server/mute.js
> chore: various fixes

- server-data/resources/[bpt_addons]/bpt_lscustom/client/main.lua
- server-data/resources/[bpt_addons]/bpt_lscustom/locales/it.lua
> chore: translation correction and update with the new SetVehicleDoorOpe natives

- server-data/resources/[bpt_addons]/bpt_policejob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_policejob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_policejob/locales/it.lua
> chore: supports new translations natively

- server-data/resources/[esx_addons]/esx-radialmenu/client/clothing.lua
- server-data/resources/[esx_addons]/esx-radialmenu/client/main.lua
- server-data/resources/[esx_addons]/esx-radialmenu/client/stretcher.lua
- server-data/resources/[esx_addons]/esx-radialmenu/client/trunk.lua
- server-data/resources/[esx_addons]/esx-radialmenu/server/trunk.lua
> chore:  update some parts of the code with the new fivem natives

- server-data/resources/[phone]/pma-voice/server/main.lua
- server-data/resources/[phone]/pma-voice/server/module/phone.lua
- server-data/resources/[phone]/pma-voice/server/module/radio.lua
- server-data/resources/[phone]/pma-voice/server/mute.js
> chore:  load the previous version of pma-voice

- server-data/resources/[bpt_addons]/bpt_pointsell/config.lua
> chore:  the sale of diamonds was implemented

- server-data/resources/[esx_addons]/esx_givevehicle/README.md
- server-data/resources/[esx_addons]/esx_givevehicle/client/main.lua
- server-data/resources/[esx_addons]/esx_givevehicle/config.lua
- server-data/resources/[esx_addons]/esx_givevehicle/fxmanifest.lua
- server-data/resources/[esx_addons]/esx_givevehicle/locales/de.lua
- server-data/resources/[esx_addons]/esx_givevehicle/locales/en.lua
- server-data/resources/[esx_addons]/esx_givevehicle/locales/tw.lua
- server-data/resources/[esx_addons]/esx_givevehicle/server/main.lua
> feat: [esx_addons]\esx_givevehicle

- server-data/resources/[ox]/ox_inventory/data/items.lua
> chore: reduced the weight of the wood

- server-data/resources/[bpt_addons]/bpt_idcard/html/assets/js/materialize.js
- server-data/resources/[esx]/esx_multicharacter/config.lua
- server-data/resources/[esx_addons]/esx_property/server/main.lua
> refactor: bpt_idcard\html\assets\js\materialize.js  Improved code formatting

- package-lock.json
- package.json
> chore(deps-dev): bump eslint from 9.9.0 to 9.11.1

- server-data/resources/[esx]/es_extended/server/classes/player.lua
> chore: Typo fix

- server-data/resources/[gameplay]/chat/html/App.ts
> Fix code scanning alert Unvalidated dynamic method call

- server-data/resources/[bpt_addons]/bpt_ambulancejob/client/job.lua
- server-data/resources/[bpt_addons]/bpt_ambulancejob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_ambulancejob/client/vehicle.lua
- server-data/resources/[bpt_addons]/bpt_ambulancejob/server/main.lua
> fix: global variable in lowercase initial

- server-data/resources/[esx_addons]/esx_scoreboard/html/listener.js
> chore: fix sanitizedMaxPlayers

- server-data/resources/[system]/[builders]/webpack/fxmanifest.lua
- server-data/resources/[system]/[builders]/webpack/webpack_builder.js
- server-data/resources/[system]/[builders]/webpack/webpack_runner.js
- server-data/resources/[system]/runcode/fxmanifest.lua
- server-data/resources/[system]/runcode/runcode.js
- server-data/resources/[system]/runcode/runcode_cl.lua
- server-data/resources/[system]/runcode/runcode_shared.lua
- server-data/resources/[system]/runcode/runcode_sv.lua
- server-data/resources/[system]/runcode/runcode_ui.lua
- server-data/resources/[system]/runcode/runcode_web.lua
- server-data/resources/[system]/runcode/web/index.html
- server-data/resources/[system]/runcode/web/nui.html
> chore: [system]\runcode 🎨 Run formatter

- server-data/resources/[bpt_addons]/bpt_ambulancejob/client/main.lua
> fixed issue with character regeneration countdown

- server-data/resources/[esx_addons]/tickets/client/main.lua
- server-data/resources/[esx_addons]/tickets/fxmanifest.lua
- server-data/resources/[esx_addons]/tickets/shared/bridge.lua
> fix: [esx_addons]/tickets fixed lint error

- server-data/resources/[esx_addons]/tickets/README.md
- server-data/resources/[esx_addons]/tickets/shared/config.lua
> chore: created the helper role for ticket management

- server-data/resources/[esx_addons]/esx_garage/config.lua
> fix: reduced the z axis to avoid vehicles spawning in the air

- server-data/resources/[ox]/ox_inventory/data/items.lua
> fix: fixed usage issue for flashlight

- server-data/resources/[esx]/fivem-appearance/web/dist/assets/index.3e1fdbaf.js
> fix: Unvalidated dynamic method call

- server-data/resources/[esx]/esx_multicharacter/client/main.lua
> fixed false godmode problem detected when relogging

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
> chore: Shotgun crafting introduced

- server-data/resources/[esx_addons]/esx_contract/client/main.lua
- server-data/resources/[esx_addons]/esx_contract/config.lua
- server-data/resources/[esx_addons]/esx_contract/locales/it.lua
- server-data/resources/[esx_addons]/esx_contract/locales/tr.lua
- server-data/resources/[esx_addons]/esx_contract/server/main.lua
- This PR takes care of correcting the Turkish translation, the English translation was called instead of the Turkish one, furthermore the Italian translation was created and configured as default.
> fix+feat: correct Turkish translation + creation of Italian translation

- server-data/resources/[esx_addons]/kc-unicorn/client/loop.lua
- server-data/resources/[esx_addons]/kc-unicorn/client/main.lua
- server-data/resources/[esx_addons]/kc-unicorn/config.lua
- server-data/resources/[esx_addons]/kc-unicorn/fxmanifest.lua
- server-data/resources/[esx_addons]/kc-unicorn/locales/en.lua
- server-data/resources/[esx_addons]/kc-unicorn/locales/fr.lua
- server-data/resources/[esx_addons]/kc-unicorn/server/main.lua
- Updated the resource export method regarding the ESX Framework
- Performed code formatting and cleaning work, removing the version check part
- fixed the problem: SCRIPT ERROR: Execution of native 00000000faa3d236 in script host failed: Tried to access invalid entity: 133121
> refactor:  major rebuild for kc-unicorn

- server-data/resources/[bpt_addons]/bpt_importjob/locales/it.lua
- In this PR the problem of the missing translation in the invoice manual for import export work is resolved
> fix: (bpt_importjob) correct missing translation

- server-data/resources/[bpt_addons]/bpt_addonaccount/LICENSE
- server-data/resources/[bpt_addons]/bpt_addonaccount/README.md
- server-data/resources/[bpt_addons]/bpt_addonaccount/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_addonaccount/server/classes/addonaccount.lua
- server-data/resources/[bpt_addons]/bpt_addonaccount/server/main.lua
In this PR the license year of the resource has been updated, also the issue of: "Undefined global `MySQL`" has been corrected, in the development environment while visual studio code was being used, the fxmanifest file has also been updated to version 1.0.3.
> fix: (bpt_addonaccount) Undefined global `MySQL`.

- server-data/resources/[ox]/ox_target/web/js/createOptions.js
> fix: correct eslint error

- server-data/resources/[esx_addons]/ptelevision/client/cursor.lua
- server-data/resources/[esx_addons]/ptelevision/client/dui.lua
- server-data/resources/[esx_addons]/ptelevision/client/main.lua
- server-data/resources/[esx_addons]/ptelevision/fxmanifest.lua
- server-data/resources/[esx_addons]/ptelevision/html/main.js
> chore: improvements for playing television content

- server-data/resources/[esx_addons]/kc-unicorn/client/main.lua
- server-data/resources/[esx_addons]/kc-unicorn/config.lua
- server-data/resources/[esx_addons]/kc-unicorn/locales/fr.lua
- server-data/resources/[esx_addons]/kc-unicorn/server/main.lua
> chore: Formatting and stability work performed

- server-data/resources/[ox]/ox_target/web/js/createOptions.js
- server-data/resources/[ox]/ox_target/web/js/main.js
- Improved the formatting of the .js code and performed a small cleanup
> chore:  improve formatting + code cleanup

- .github/dependabot.yml
> chore:  update depandabot to scan yarn dependencies

- server-data/resources/[gameplay]/chat/package.json
- server-data/resources/[gameplay]/chat/yarn.lock
> chore: add loader-utils

- server-data/resources/[esx_addons]/ps-dispatch/ui/app.js
> chore:  carried out code formatting and stability work

- server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua
> fix: (bpt_ammujob) accessing undefined variable elements

- server-data/resources/[esx_addons]/esx_scoreboard/html/listener.js
> chore:  client-side cross-site scripting fix

- server-data/resources/[sound_cars]/bmwSound440-M3-M4-S58/fxmanifest.lua
- server-data/resources/[sound_cars]/ktm1290r/fxmanifest.lua
- server-data/resources/[test]/fivem/fxmanifest.lua
> chore: ([test]\fivem)🎨 Run formatter

- server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/config.lua
- server-data/resources/[gameplay]/player-data/fxmanifest.lua
- server-data/resources/[gameplay]/player-data/server.lua
- server-data/resources/[sound_cars]/Mads14Sound/fxmanifest.lua
- server-data/resources/[sound_cars]/Skyline_SoundGT-R/fxmanifest.lua
- server-data/resources/[sound_cars]/lg116slsamg/fxmanifest.lua
- server-data/resources/[sound_cars]/tamustanggt50/fxmanifest.lua
- server-data/resources/[wasabi]/wasabi_oxshops/configuration/config.lua
> patch fix 1.0.7 v1

- server-data/resources/[esx]/es_extended/client/modules/afk.lua
- server-data/resources/[esx]/es_extended/server/modules/afk.lua
> chore:  introduced an anti afk system

- server-data/resources/[esx]/pushvehicle/client/main.lua
- server-data/resources/[esx]/pushvehicle/fxmanifest.lua
- server-data/resources/[esx]/pushvehicle/server/main.lua
- server-data/resources/[esx]/pushvehicle/shared/config.lua
> chore: use ox_target to push the vehicle

- server-data/resources/[bpt_addons]/bpt_policejob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_policejob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_policejob/locales/it.lua
> chore: (bpt_policejob) introduces the prison menu to the police f6 menu

- server-data/resources/[bpt_addons]/bpt_policejob/client/main.lua
> fix: (bpt_policejob) corrected typo

- server-data/resources/[bpt_addons]/bpt_policejob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_policejob/locales/it.lua
> chore: (bpt_policejob)  removed some unused translations

- server-data/resources/[esx_addons]/ps-dispatch/ui/app.js
> chore: Client-side cross-site scripting

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
- server-data/resources/[esx]/es_extended/locales/en.lua
- server-data/resources/[esx]/es_extended/shared/config/weapons.lua
> feat: WEAPON_PISTOL_MK2

- server-data/resources/[esx_addons]/kc-unicorn/client/main.lua
- server-data/resources/[esx_addons]/kc-unicorn/server/main.lua
> fix: (kc_unicorn) Tried to access invalid entity: 133121

- server-data/resources/[esx_addons]/seatbelt/fxmanifest.lua
- server-data/resources/[esx_addons]/seatbelt/html/app.js
- server-data/resources/[esx_addons]/seatbelt/main.lua
> chore: code cleaning and js formatting

- server-data/resources/[ox]/ox_inventory/data/shops.lua
> chore: new shops have been added for purchasing food

- server-data/[SQL]/es_extended.sql
Changing the HediSQL and the S.O server to make it work with the latest version
Fixes #[#966]
> Update es_extended.sql 

- server-data/resources/[bpt_addons]/bpt_addoninventory/server/main.lua
> fix:  functions had a maximum of 0 arguments

- server-data/resources/[bpt_addons]/bpt_backpack/client/client.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_bakerjob/server/main.lua
- server-data/resources/[phone]/pma-voice/package-lock.json
- server-data/resources/[phone]/pma-voice/package.json
- server-data/resources/[phone]/pma-voice/yarn.lock
> fix: (bpt_backpack) CreateObjectNoOffset

- server-data/resources/[esx_addons]/xt-robnpcs/bridge/client/esx.lua
- server-data/resources/[esx_addons]/xt-robnpcs/bridge/client/ox.lua
- server-data/resources/[esx_addons]/xt-robnpcs/bridge/client/qb.lua
- server-data/resources/[esx_addons]/xt-robnpcs/bridge/server/ox.lua
- server-data/resources/[esx_addons]/xt-robnpcs/client/cl_main.lua
- server-data/resources/[esx_addons]/xt-robnpcs/client/utils.lua
- Removed GiveWeaponToPed as it caused automatic banning by the anticheat when an NPC was robbed
> fix:  removed the GiveWeaponToPed

- server-data/resources/[phone]/pma-voice/package-lock.json
- server-data/resources/[phone]/pma-voice/package.json
- server-data/resources/[phone]/pma-voice/voice-ui/pnpm-lock.yaml
- server-data/resources/[phone]/pma-voice/yarn.lock
- Replaced "hapi/address" with "sideway/address" and "hapi/joi" with "joi"
> chore: update dependencies

- server-data/resources/[phone]/pma-voice/package-lock.json
- server-data/resources/[phone]/pma-voice/package.json
- server-data/resources/[phone]/pma-voice/yarn.lock
> chore: update hapi/bourne  version 3.0.0

- server-data/resources/[phone]/z-phone/web/src/utils/common.js
> fix: Use the isNaN function to compare with NaN

- server-data/resources/[gameplay]/chat/cl_chat.lua
- server-data/resources/[gameplay]/chat/fxmanifest.lua
- server-data/resources/[gameplay]/chat/sv_chat.lua
- server-data/resources/[gameplay]/chat/webpack.config.js
> chore:  formatting works & fixes of problems reported by CI Lint

- server-data/resources/[phone]/pma-voice/package-lock.json
- server-data/resources/[phone]/pma-voice/package.json
- server-data/resources/[phone]/pma-voice/voice-ui/pnpm-lock.yaml
- server-data/resources/[phone]/pma-voice/yarn.lock
> chore:  replaced hapi/bourne library with sinclair/typebox

- server-data/resources/[bpt_addons]/bpt_backpack/server/server.lua
> fix unused loop variable i

- server-data/resources/[phone]/pma-voice/fxmanifest.lua
- server-data/resources/[phone]/pma-voice/package-lock.json
- server-data/resources/[phone]/pma-voice/package.json
- server-data/resources/[phone]/pma-voice/yarn.lock
> chore: update loader-utils

- .github/dependabot.yml
- These improvements should help manage dependencies more efficiently and ensure that updates are reviewed and merged in a timely manner.
> chore:  update the dependabot

- server-data/resources/[phone]/npwd/resources/dist/client/client.js
> fix: ReferenceError: Cannot access 'playerPed' before initialization

- server-data/resources/[system]/[builders]/webpack5/package.json
- server-data/resources/[system]/[builders]/webpack5/yarn.lock
> fix: Cross-site Scripting (XSS) in serialize-javascript

- server-data/resources/[bpt_addons]/bpt_mechanicjob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_policejob/fxmanifest.lua
- server-data/resources/[esx_addons]/ars_billing/server/server.lua
- server-data/resources/[ox]/ox_inventory/data/items.lua
- server-data/resources/[ox]/ox_inventory/fxmanifest.lua
> chore:  small fixes for the billing system

- server-data/resources/[ox]/ox_inventory/data/licenses.lua
> chore:  removed the purchase of the weapon license as it was duplicated

- server-data/resources/[bpt_addons]/bpt_dmvschool/html/questions_it.js
> fix:  corrected typo

- server-data/resources/[esx_addons]/esx_lumberjack/fxmanifest.lua
> chore: import es_extended/locale.lua as a shared file

- server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/locales/it.lua
- server-data/resources/[esx_addons]/cc-chat/fxmanifest.lua
- server-data/resources/[system]/hardcap/client.lua
- server-data/resources/[system]/hardcap/server.lua
> refactor: (bpt_ammujob) removed the billing system from the f6 menu

- server-data/resources/[bpt_addons]/bpt_ballasjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_ballasjob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_ballasjob/locales/it.lua
> refactor: (bpt_ballas) removed the billing system from the f6 menu

- server-data/resources/[bpt_addons]/bpt_mechanicjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/locales/it.lua
> refactor: (bpt_mechanicjob) removed the billing system from the f6 menu

- server-data/resources/[bpt_addons]/bpt_mechanicjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/fxmanifest.lua
> chore: (bpt_mechanicjob) fixed error loading translations

- server-data/resources/[esx_addons]/esx_vehicleshop/client/main.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/client/npc.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/client/utils.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/config.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/server/main.lua
> refactor: (esx_vehicleshop) improves the stability of the dealer's work

- server-data/resources/[esx]/bpt_society/client/main.lua
- server-data/resources/[esx]/bpt_society/server/main.lua
> chore: (bpt_society) reworks the corporate system by correcting the recycling system

- server-data/resources/[sqz]/sqz_carkeys/client/client.lua
- server-data/resources/[sqz]/sqz_carkeys/fxmanifest.lua
- server-data/resources/[sqz]/sqz_carkeys/server/server.lua
> fix:  (sqz_carkeys) corrected importing of translations

- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
> chore:  skill the construction of diamond tips at the ballas

- server-data/resources/[esx]/bpt_society/client/main.lua
- server-data/resources/[esx]/bpt_society/server/main.lua
> chore:  restored the previous version of bpt_society

- server-data/resources/[ox]/ox_inventory/data/stashes.lua
> chore: increases the permitted weight capacity

- server-data/resources/[ox]/ox_inventory/data/items.lua
> chore:  weight balance

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
- server-data/resources/[esx_addons]/esx_vehicleshop/client/main.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/client/utils.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/config.lua
- server-data/resources/[esx_addons]/esx_vehicleshop/server/main.lua
> Added creation of torches for weapons

- server-data/resources/[bpt_addons]/bpt_wallet/config.lua
- server-data/resources/[bpt_addons]/bpt_wallet/server/server.lua
> chore: prevent wallets from being nested inside each other

- server-data/resources/[sqz]/sqz_carkeys/client/client.lua
> fix: fixed double translation issue

- server-data/resources/[bpt_addons]/bpt_boat/server/main.lua
ParkBoats function: Handles parking of all boats not saved in the database, updating the stored field to true for those boats that were still out of the garage. 
Callback bpt_boat:buyBoat: Checks if the player has enough money to buy a boat and updates the database to mark the boat as purchased. If the price is 0 (bad model), it signals an exploit attempt.
Event bpt_boat:takeOutVehicle: When a player wants to take a boat from the garage, the function updates the database to mark the boat as "out" of the garage (stored = false).
Callback bpt_boat:storeVehicle: Handles the logic to park the boat in the garage, updating the database to mark the boat as "in garage" (stored = true).
Callback bpt_boat:getGarage: Returns all boats saved in a player's garage, loading the data from the database. …
> refactor: bpt_boat\server\main.lua

- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
> fix: correct position of the work table

- server-data/resources/[esx]/mythic_notify/html/js/app.js
> fix: (mythic_notify) Client-side cross-site scripting

- server-data/resources/[bpt_addons]/bpt_autovelox/database/multe.sql
- server-data/resources/[bpt_addons]/bpt_autovelox/server/main.lua
- The proceeds of the fines will be paid into the police account, the speed cameras will only work if the police are online.
> chore:  improves the gaming experience

- server-data/resources/[sqz]/sqz_carkeys/client/client.lua
> chore: fixed the creation of blips in the map

- server-data/resources/[bpt_addons]/bpt_boat/README.md
> chore: (bpt_boat\README.md) Update copyright year

- server-data/resources/[bpt_addons]/bpt_idcard/LICENSE
- server-data/resources/[bpt_addons]/bpt_idcard/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_idcard/html/assets/js/materialize.js
> chore: improved formatting + update license year and version

- server-data/resources/[bpt_addons]/bpt_RealisticVehicle/config.lua
- server-data/resources/[bpt_addons]/bpt_RealisticVehicle/fxmanifest.lua
> chore: minor corrections and description update

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
- server-data/resources/[bpt_addons]/bpt_vehicletax/server/server.lua
- server-data/resources/[managers]/spawnmanager/fxmanifest.lua
- server-data/resources/[managers]/spawnmanager/spawnmanager.lua
> fix: (bpt_vehicletax) corrected typo

- server-data/resources/[ox]/ox_inventory/data/items.lua
> chore: update items.lua

- server-data/resources/[bpt_addons]/bpt_crafting/bpt_crafting.sql
- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
- server-data/resources/[bpt_addons]/bpt_crafting/localization/bpt_crafting_it.sql
> chore: add (bpt_crafting) weapon_tecpistol

- server-data/resources/[bpt_addons]/bpt_unicornjob/client/main.lua
> fix: fixed issue that allowed recycling to be displayed

- server-data/resources/[wasabi]/wasabi_oxshops/configuration/config.lua
- server-data/resources/[wasabi]/wasabi_oxshops/fxmanifest.lua
> chore: removal of automatic shop for import export

- server-data/resources/[bpt_addons]/bpt_bennysjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_bennysjob/config.lua
- server-data/resources/[bpt_addons]/bpt_lscustom/client/main.lua
- server-data/resources/[bpt_addons]/bpt_lscustom/config.lua
> chore: (bpt_bennysjob + bpt_lscustom) removed double blip on map

- server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua
> fix: (bpt_ammujob) fix undefined marker errors

- server-data/resources/[bpt_addons]/bpt_investments/LICENSE
- server-data/resources/[bpt_addons]/bpt_investments/client/client.lua
- server-data/resources/[bpt_addons]/bpt_investments/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_investments/readme.md
- server-data/resources/[bpt_addons]/bpt_investments/server/server.lua
Description
This pull request introduces a new Stock Market Investment System for FiveM ESX-based servers, fully integrated with ox_lib and ox_target.
Players can invest money through an in-game NPC once every 24 hours. The investment outcome is randomized, simulating real-world stock market risk, offering a chance to gain or lose part of the invested amount.
Features
🏦 - Stock investment zone with interactive NPC
⏳- 24-hour cooldown per player
🎲- Randomized outcome: profit or loss
🧱 - Uses ox_lib for UI dialogs and notifications
🎯 ox_target for precise interaction
🔒 - Server-side validation for secure transactions
Author
Created by bitpredator.
> feat: Add stock market investment system with 24h cooldown using ESX, ox_lib, and ox_target

- .github/dependabot.yml
> chore: remove reviewers

- server-data/resources/[bpt_addons]/bpt_investments/client/client.lua
- server-data/resources/[bpt_addons]/bpt_investments/fxmanifest.lua
> fix: fix bpt_investments resource startup problems

- server-data/resources/[wasabi]/wasabi_oxshops/client/client.lua
- server-data/resources/[wasabi]/wasabi_oxshops/configuration/config.lua
- server-data/resources/[wasabi]/wasabi_oxshops/server/server.lua
> chore: correct coordinates for hospital store

- server-data/resources/[bpt_addons]/bpt_pointsell/README.md
- server-data/resources/[bpt_addons]/bpt_pointsell/client/main.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/config.lua
- server-data/resources/[bpt_addons]/bpt_pointsell/fxmanifest.lua
> chore: set max quantity to 5k use an updated coordinate system

- server-data/resources/[esx_addons]/xsound/addon/crewphone/client/client.lua
- server-data/resources/[esx_addons]/xsound/addon/crewphone/server/server.lua
- server-data/resources/[esx_addons]/xsound/addon/readme.md
- server-data/resources/[esx_addons]/xsound/client/commands.lua
- server-data/resources/[esx_addons]/xsound/client/effects/main.lua
- server-data/resources/[esx_addons]/xsound/client/emulator/interact_sound/client.lua
- server-data/resources/[esx_addons]/xsound/client/events.lua
- server-data/resources/[esx_addons]/xsound/client/exports/events.lua
- server-data/resources/[esx_addons]/xsound/client/exports/info.lua
- server-data/resources/[esx_addons]/xsound/client/exports/manipulation.lua
- server-data/resources/[esx_addons]/xsound/client/exports/play.lua
- server-data/resources/[esx_addons]/xsound/client/main.lua
- server-data/resources/[esx_addons]/xsound/config.lua
- server-data/resources/[esx_addons]/xsound/fxmanifest.lua
- server-data/resources/[esx_addons]/xsound/html/index.html
- server-data/resources/[esx_addons]/xsound/html/scripts/SoundPlayer.js
- server-data/resources/[esx_addons]/xsound/html/scripts/functions.js
- server-data/resources/[esx_addons]/xsound/html/scripts/listener.js
- server-data/resources/[esx_addons]/xsound/license.txt
- server-data/resources/[esx_addons]/xsound/readme.md
- server-data/resources/[esx_addons]/xsound/server/emulator/interact_sound/server.lua
- server-data/resources/[esx_addons]/xsound/server/exports/manipulation.lua
- server-data/resources/[esx_addons]/xsound/server/exports/play.lua
> feat: introduce xsound for proper radio operation in vehicles

- server-data/resources/[bpt_addons]/bpt_autovelox/client/main.lua
- server-data/resources/[bpt_addons]/bpt_autovelox/config.lua
- server-data/resources/[bpt_addons]/bpt_autovelox/database/multe.sql
- server-data/resources/[bpt_addons]/bpt_autovelox/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_autovelox/license.txt
- server-data/resources/[bpt_addons]/bpt_autovelox/readme.md
- server-data/resources/[bpt_addons]/bpt_autovelox/server/main.lua
This PR introduces a complete dynamic speed camera system for ESX-based FiveM RP servers.
Key Features:
- Speed cameras randomly rotate between predefined positions every 10 minutes.
- Automatic speed detection and fine calculation based on the local speed limit.
- Fine is automatically deducted from the player’s bank account.
- If the player lacks sufficient funds, a vehicle is marked as "seized" and becomes unusable.
- Players can pay the fine later using the `/payfine` command to unlock the seized vehicle.
- All collected fines are transferred directly to the `society_government` account.
- Integrated with `ox_lib` for better notifications (optional).
Database:
- Adds a new column `blocked_for_fine` to the `owned_vehicles` table.
This system is designed to enhance immersion, enforce …
> ✨ Add Dynamic Speed Camera System with Fines and Vehicle Seizure (ESX)

- server-data/resources/[bpt_addons]/bpt_loadscreen/LICENSE
- server-data/resources/[bpt_addons]/bpt_loadscreen/README.md
- server-data/resources/[bpt_addons]/bpt_loadscreen/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_loadscreen/index.html
- server-data/resources/[bpt_addons]/bpt_loadscreen/script/main.js
This repository contains the updated and optimized loadscreen for EmpireTown RP.
- Replaced external YouTube embed with a locally hosted `video.mp4` background.
- Modernized JavaScript (`main.js`) with better performance, volume control, and cleaner logic.
- Removed deprecated practices and ensured full compatibility with modern browsers.
- Updated `fxmanifest.lua` to include all required assets, including the local video.
💡 Lightweight, fast, and fully RP-immersive.
> EmpireTown Custom Loadscreen – Local Video & JS Refactor

- server-data/resources/[gameplay]/chat/html/App.js
This update enhances the security of the chat system by introducing a strict whitelist for dynamically called methods via the `message` event listener. It prevents the execution of unverified function calls, reducing the risk of client-side injection or unintended behavior.
Changes:
- Added a whitelist for allowed event types (`ON_OPEN`, `ON_TIME`, etc.).
- Replaced unsafe dynamic method invocation (`this[item.type]`) with validated access.
- Improved code readability and maintainability.
Recommended for all users integrating this chat system in their FiveM RP servers.
> Improve Event Handling Security in Chat Component

- server-data/resources/[esx_addons]/xsound/fxmanifest.lua
- server-data/resources/[esx_addons]/xsound/html/scripts/functions.js
This pull request refactors the code responsible for handling music URLs, parsing YouTube video IDs, and retrieving audio durations. Key improvements include:
- Replaced unsafe string manipulations with modern and secure URL object parsing.
- Removed redundant and insecure HTML tag stripping from URLs.
- Properly destroyed YouTube player instances and audio objects to prevent memory leaks.
- Added robust error handling and URL validation via try/catch.
- Improved logic for YouTube URL detection and video ID extraction.
- Minor code cleanups and modern JavaScript practices (e.g., const, let, arrow functions).
These changes improve code safety, maintainability, and cross-platform consistency. …
> Refactor and Secure Music URL Handling + YouTube ID Parsing

- server-data/resources/[esx_addons]/xsound/html/scripts/functions.js
This pull request introduces major improvements to the security, reliability, and readability of music URL handling and YouTube video ID extraction.
Key changes:
- ✅ Secure YouTube domain validation using an explicit whitelist.
- 🧼 Removed unsafe HTML sanitization from URL handling.
- 🧩 Rewritten getYoutubeUrlId with native URL parsing and proper error handling.
- 🗑️ Temporary YouTube players are now correctly removed from the DOM after use.
- 🔊 Improved handling of invalid audio sources and duration retrieval.
- ⚙️ General refactoring using modern JavaScript practices (e.g., const, let, arrow functions).
These improvements enhance the codebase’s safety, prevent future bugs, and make it easier to maintain.
**Please describe the changes this PR makes and why it should be …
> Secure and Refactor Music URL Parsing and YouTube ID Extraction

- server-data/resources/[phone]/npwd/resources/dist/client/client.js
This pull request fixes syntax issues and improves configuration handling in the client/client.js module
✅ Major changes:
Fixed a syntax error in the JSON.parse(LoadResourceFile(...)) block.
- Improved error handling with try/catch to avoid crashes from invalid JSON.
- Optimized the use of LoadResourceFile to avoid unnecessary double calls.
- Check for the presence of properties with hasOwnProperty.
- Clearer and more informative logging in case of error (console.warn).
🔒 Security:
Prevent client-side crashes in case of corrupt or missing JSON configuration.
Robust validation for npwd:phoneAsItem convar data.
> Fix config loader and JSON parsing security improvements

- server-data/resources/[bpt_addons]/bpt_crafting/config.lua
> chore: doctors' ability to work with herbs removed

- server-data/resources/[ox]/ox_inventory/data/items.lua
> chore: change the weight of cigarette papers

- server-data/resources/[bpt_addons]/bpt_banking/client/main.lua
- server-data/resources/[bpt_addons]/bpt_banking/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_banking/html/scripts/app.js
- server-data/resources/[bpt_addons]/bpt_banking/server/main.lua
This update provides a secure and modular JavaScript file for FiveM-based banking interfaces. It includes HTML escaping to prevent XSS, validation of user input, replacement of deprecated methods, and a structured rendering system using safe template literals. Designed to integrate smoothly with ESX or custom server logic, this file is optimized for both safety and maintainability.
> Secure Frontend Logic for Banking UI

- server-data/resources/[maps]/ajaxon_burton_lsc/fxmanifest.lua
A custom high-quality MLO map of the iconic ajaxon_burton_lsc for FiveM. Includes YMAP, YDR, YBN, YTYP, and other necessary map files. Optimized for seamless integration and immersive roleplay environments.
> ajaxon_burton_lsc MLO - FiveM Map

- server-data/resources/[maps]/bennys/fxmanifest.lua
- server-data/resources/[maps]/gabz_mrpd/fxmanifest.lua
- server-data/resources/[maps]/gabz_mrpd/gabz_mrpd_entitysets.lua
- server-data/resources/[maps]/gabzemsv2/main.lua
A custom high-quality MLO map of the iconic for FiveM. Includes YMAP, YDR, YBN, YTYP, and other necessary map files. Optimized for seamless integration and immersive roleplay environments.
> gabz_mrpd + benny's MLO - FiveM Map

- server-data/resources/[maps]/bob74_ipl/client.lua
- server-data/resources/[maps]/bob74_ipl/dlc_finance/office1.lua
- server-data/resources/[maps]/bob74_ipl/dlc_finance/office4.lua
- server-data/resources/[maps]/bob74_ipl/dlc_gunrunning/bunkers.lua
- server-data/resources/[maps]/bob74_ipl/dlc_gunrunning/yacht.lua
- server-data/resources/[maps]/bob74_ipl/dlc_tuner/meetup.lua
> chore: (bob74_ipl\dlc_finance) 🎨 Run formatter

- server-data/resources/[maps]/gabzemsv2/fxmanifest.lua
- server-data/resources/[maps]/gabzemsv2/main.lua
- ✅ Replaced `Citizen.CreateThread` with the modern `CreateThread` syntax.
- 📍 Used `vector3` directly with `GetInteriorAtCoords` for cleaner coordinate handling.
- 🔁 Switched from `pairs` to `ipairs` for more predictable IPL iteration.
- 🧹 Removed default GTA hospital IPLs:
- `rc12b_fixed`
- `rc12b_destroyed`
- `rc12b_default`
- `rc12b_hospitalinterior_lod`
- `rc12b_hospitalinterior`
- 📝 Added inline comments for better readability and future maintenance.
- ⚠️ Added a debug warning if the interior ID is invalid.
These changes ensure better performance and full compatibility with **Gabz Pillbox MLO**, while making the codebase more readable and maintainable.
Discord username (if different from …
> Refactored Pillbox Interior Loading for Gabz Compatibility and Cleaner Code

- server-data/resources/[maps]/five3devs_vanilla/fxmanifest.lua
- server-data/resources/[maps]/gabzemsv2/fxmanifest.lua
- server-data/resources/[maps]/iak_ammunation/fxmanifest.lua
- server-data/resources/[maps]/int_prisonfull/client.lua
- server-data/resources/[maps]/int_prisonfull/fxmanifest.lua
- server-data/resources/[maps]/prisonprops/fxmanifest.lua
- server-data/resources/[maps]/vinyard/fxmanifest.lua
> fix: (fix stylua check) vinyard\fxmanifest.lua

- server-data/resources/[esx_addons]/wx_rpchat/client/chat_client.lua
- server-data/resources/[esx_addons]/wx_rpchat/client/fontinit.lua
- server-data/resources/[esx_addons]/wx_rpchat/client/functions.lua
- server-data/resources/[esx_addons]/wx_rpchat/client/reports.lua
- server-data/resources/[esx_addons]/wx_rpchat/client/status.lua
- server-data/resources/[esx_addons]/wx_rpchat/client/suggestions.lua
- server-data/resources/[esx_addons]/wx_rpchat/configs/chat_config.lua
- server-data/resources/[esx_addons]/wx_rpchat/configs/webhook_config.lua
- server-data/resources/[esx_addons]/wx_rpchat/fxmanifest.lua
- 🎭 `/me`, `/do`, `/doa` 3D text rendering visible only within proximity
- 💬 Local OOC with admin badge and styled HTML messages
- 🚫 Cooldown system to prevent spam
- 🔒 Admin group detection via server callback
- 📐 Dynamic display offset for overlapping 3D messages
- 🎨 Uses custom font `BBN` for stylish appearance
- 🧱 Modular and optimized Lua code
> wx_rpchat - Advanced 3D RP Chat System for FiveM

- server-data/resources/[gameplay]/[examples]/money-fountain/client.lua
- server-data/resources/[gameplay]/[examples]/money-fountain/fxmanifest.lua
- server-data/resources/[gameplay]/[examples]/money-fountain/mapdata.lua
- server-data/resources/[gameplay]/[examples]/money-fountain/server.lua
This pull request improves the logic and performance of the `money_fountain` server-side script. Key enhancements include:
- 🔁 Cleaned up redundant code for better readability and maintainability.
- 📦 Improved handling of KVP-based money storage.
- 🚀 Optimized player proximity checks for better performance.
- 🧠 Separated logic into clear, reusable functions (`getMoneyForFountain`, `setMoneyForFountain`, etc.).
- 🔒 Added more robust validation for cooldowns and interaction conditions.
- 🔄 Ensured real-time synchronization with `GlobalState` only when necessary.
The current implementation was functional but lacked modularity and efficiency. These improvements aim to:
- Make the system easier to extend or debug.
- Reduce performance overhead on both client and server.
- Prepare the …
> ✨ Improved Money Fountain Logic and Server Optimization

- server-data/resources/[gamemodes]/interact-sound/LICENSE
- server-data/resources/[gamemodes]/interact-sound/client/html/index.html
- server-data/resources/[gamemodes]/interact-sound/client/main.lua
- server-data/resources/[gamemodes]/interact-sound/fxmanifest.lua
- server-data/resources/[gamemodes]/interact-sound/server/main.lua
This pull request enhances the NUI sound playback system by:
- Replacing `pause()` with `stop()` to ensure proper interruption of previous sounds.
- Adding volume normalization and input validation (range 0.1 - 1.0).
- Implementing error handling via `onloaderror` and `onplayerror` callbacks.
- Improving code readability and structure.
- Adding proper language and meta tags to the HTML structure.
These changes ensure smoother and more reliable in-game sound playback, especially in cases where multiple sounds are triggered in quick succession.
Previously, overlapping sounds could play or fail to stop properly due to improper handling of `Howl` instances. This update ensures clean audio transitions, more robust volume control, and better debugging when sound files fail to load or play. …
> 🚀 Improve NUI Audio Playback Logic with Howler.js

- server-data/resources/[bpt_addons]/bpt_ammujob/README.md
- server-data/resources/[bpt_addons]/bpt_ammujob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_ammujob/locales/it.lua
This pull request introduces the new invoicing system via f6 menu for armory work, also the new discord link has been added for the multigaming community
> chore: New invoicing system via F6 menu + new Discord link

- server-data/resources/[bpt_addons]/bpt_mechanicjob/LICENSE
- server-data/resources/[bpt_addons]/bpt_mechanicjob/README.md
- server-data/resources/[bpt_addons]/bpt_mechanicjob/client/main.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/fxmanifest.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/locales/en.lua
- server-data/resources/[bpt_addons]/bpt_mechanicjob/locales/it.lua
> chore: Implement the billing system in bpt_mechanicjob

- server-data/resources/[phone]/z-phone/client/feature/inetmax.lua
- server-data/resources/[phone]/z-phone/client/feature/loops.lua
> fixed issue with social media posts not being created

- server-data/resources/[bpt_addons]/bpt_mechanicjob/client/main.lua
Correction of mechanical invoice sending, the event used was incorrect
> fix: correction of sending invoice to mechanic

- server-data/resources/[bpt_addons]/bpt_lscustom/client/main.lua
- server-data/resources/[bpt_addons]/bpt_lscustom/config.lua
- server-data/resources/[bpt_addons]/bpt_lscustom/server/main.lua
> chore: corrected the position of the change center

- server-data/resources/[bpt_addons]/bpt_ambulancejob/README.md
- server-data/resources/[bpt_addons]/bpt_ambulancejob/client/job.lua
- server-data/resources/[bpt_addons]/bpt_ambulancejob/config.lua
- server-data/resources/[bpt_addons]/bpt_ambulancejob/locales/it.lua
- Bug fixes related to vehicle purchasing
- Invoicing system introduced for doctors
Fixes #1250
> fix: fix error ( Out of onesync range )

- server-data/resources/[esx_addons]/esx_garage/client/main.lua
- server-data/resources/[esx_addons]/esx_garage/esx_garage.sql
- server-data/resources/[esx_addons]/esx_garage/server/main.lua
🛠 Event safety fix: replaced the insecure esx_garage:setImpound net event with a fully server-handled implementation, ensuring safe and reliable vehicle ownership validation.
🚗 Wrong vehicle issue resolved: fixed the bug where players could retrieve vehicles that were not theirs. Now only the correct owned vehicle is spawned.
🛞 Large vehicle spawn fix: adjusted dynamic Z-axis handling to prevent large vehicles from spawning stuck in the ground due to tire collisions.
💰 Dynamic impound fees: added a new feature where the impound fee increases the longer the vehicle remains in the pound.
The more time passes, the higher the cost to release the vehicle.
Adds realism and encourages players to retrieve vehicles sooner.
🔒 Server-side validation improvements: improved handling of vehicleProps, …
> 🔧 Fix & Feature Update: Vehicle Impound System Improvements

- server-data/resources/[ox]/ox_inventory/data/items.lua
> chore: balancing food status
